prepare:
  image: maven:3.8.4-openjdk-11-slim
  command: [ "mvn" ]
  args: [ "clean", "package" ]
pipeline:
  image: maven:3.8.4-openjdk-11-slim
  command: [ "java" ]
  args: [ "-jar", "target/pipeline.jar" ]
  env:
    - name: SONAR_TOKEN
      valueFrom:
        secretKeyRef:
          name: sonarqube-auth
          key: token
    - name: PGP_PASSPHRASE
      valueFrom:
        secretKeyRef:
          name: pgp-sign
          key: passphrase
    - name: SONAR_URL
      value: http://sonarqube-sonarqube.sonarqube.svc.cluster.local:9000
